USE lexi_leap;
INSERT INTO word (spell, definition_cn, definition_en, example_sentence) VALUES
('abundant', '丰富的', 'existing or available in large quantities', 'The region has abundant natural resources.'),
('acerbic', '尖刻的', 'having a sharp or critical quality', 'He gave an acerbic critique of the proposal.'),
('acquiescent', '默认的', 'ready to accept something without protest', 'She was acquiescent in her partner''s decision.'),
('adamant', '坚定的', 'refusing to be persuaded', 'He was adamant about not changing his mind.'),
('adroit', '灵巧的', 'clever and skillful', 'She is an adroit negotiator.'),
('aesthetic', '美学的', 'concerned with beauty', 'The building has an aesthetic appeal.'),
('altruistic', '利他的', 'showing a disinterested concern for others', 'He made an altruistic donation to the charity.'),
('ambiguous', '模糊的', 'open to more than one interpretation', 'The instructions were ambiguous and confusing.'),
('ameliorate', '改善', 'make (something bad or unsatisfactory) better', 'We need to ameliorate the living conditions.'),
('analytical', '分析的', 'relating to or using analysis', 'An analytical approach is needed to solve this problem.'),
('anomalous', '异常的', 'deviating from what is standard', 'The results showed an anomalous pattern.'),
('antagonistic', '敌对的', 'showing or feeling active opposition', 'The two groups had an antagonistic relationship.'),
('apathetic', '冷漠的', 'showing or feeling no interest', 'Many young people are apathetic about politics.'),
('apprehensive', '忧虑的', 'anxious or fearful', 'She was apprehensive about the outcome.'),
('arduous', '艰巨的', 'involving strenuous effort', 'Climbing the mountain is an arduous task.'),
('articulate', '表达清晰的', 'having or showing the ability to speak clearly', 'She gave an articulate speech.'),
('ascetic', '苦行的', 'practicing strict self-denial', 'He led an ascetic lifestyle.'),
('assiduous', '勤奋的', 'showing great care and perseverance', 'She is an assiduous student.'),
('audacious', '大胆的', 'showing a willingness to take risks', 'He made an audacious proposal.'),
('auspicious', '吉利的', 'indicating a good chance of success', 'The project started under auspicious circumstances.'),
('authoritative', '权威的', 'having or showing authority', 'The report is an authoritative source of information.'),
('avaricious', '贪婪的', 'having an extreme desire for wealth', 'The avaricious businessman exploited his workers.'),
('banal', '平庸的', 'lacking originality', 'The movie had a banal plot.'),
('belligerent', '好战的', 'hostile and aggressive', 'The belligerent nation refused to negotiate.'),
('benevolent', '仁慈的', 'kind and generous', 'The benevolent millionaire donated to many causes.'),
('bombastic', '夸大的', 'using high-sounding but empty words', 'His bombastic speech impressed no one.'),
('burgeoning', '迅速发展的', 'beginning to grow or increase rapidly', 'The city has a burgeoning tech industry.'),
('cacophonous', '刺耳的', 'loud and unpleasant', 'The cacophonous noise from the street kept me awake.'),
('callous', '无情的', 'showing no concern for others', 'His callous remarks hurt her feelings.'),
('candid', '坦率的', 'truthful and straightforward', 'She gave a candid opinion about the situation.'),
('capricious', '反复无常的', 'changing suddenly', 'The capricious weather made planning difficult.'),
('cautious', '谨慎的', 'avoiding potential risks', 'He took a cautious approach to the problem.'),
('chimerical', '空想的', 'existing only as the product of imagination', 'His chimerical ideas were never realized.'),
('circumspect', '谨慎的', 'wary and unwilling to take risks', 'A circumspect investor avoids high-risk ventures.'),
('cohesive', '有凝聚力的', 'uniting or working well together', 'The team showed a cohesive effort.'),
('colloquial', '口语的', 'used in ordinary or familiar conversation', 'Colloquial expressions are common in daily speech.'),
('compassionate', '富有同情心的', 'feeling or showing sympathy', 'The compassionate nurse cared for her patients.'),
('complacent', '自满的', 'showing smug satisfaction', 'The complacent team underestimated their opponents.'),
('conciliatory', '调和的', 'intended to resolve conflict', 'He made a conciliatory gesture.'),
('conducive', '有益的', 'making a certain situation or outcome likely', 'A quiet environment is conducive to study.'),
('confounded', '困惑的', 'completely bewildered', 'He was confounded by the complex problem.'),
('convoluted', '复杂的', 'extremely complex and difficult to follow', 'The convoluted plot made the movie hard to understand.'),
('cursory', '粗略的', 'hasty and not thorough', 'He gave the report a cursory glance.'),
('daunting', '令人畏惧的', 'seeming difficult to deal with', 'The task of climbing the mountain was daunting.'),
('decorous', '得体的', 'in keeping with good taste', 'Her decorous behavior impressed everyone.'),
('definitive', '决定性的', 'authoritative and conclusive', 'This is the definitive guide to the subject.'),
('deleterious', '有害的', 'causing harm or damage', 'Smoking has a deleterious effect on health.'),
('delineated', '清晰描绘的', 'clearly described or outlined', 'The boundaries of the project were delineated.'),
('demanding', '要求高的', 'needing a great deal of effort', 'The demanding job required long hours.'),
('derivative', '派生的', 'imitative of the work of others', 'The movie''s plot was derivative and unoriginal.'),
('despondent', '沮丧的', 'in low spirits', 'He became despondent after failing the exam.'),
('dexterous', '灵巧的', 'skillful with the hands', 'The dexterous surgeon performed the operation.'),
('diligent', '勤奋的', 'having or showing care', 'The diligent student studied every night.'),
('discernible', '可辨别的', 'able to be perceived', 'There was a discernible change in his attitude.'),
('discerning', '有洞察力的', 'having good judgment', 'A discerning critic can spot quality.'),
('disinterested', '公正的', 'impartial and unbiased', 'A disinterested third party mediated the dispute.'),
('divergent', '分歧的', 'tending to be different', 'The two theories have divergent views.'),
('dogmatic', '教条的', 'asserting opinions', 'He was criticized for his dogmatic approach.'),
('ebullient', '热情洋溢的', 'cheerful and full of energy', 'The ebullient crowd cheered the team.'),
('eclectic', '折中的', 'derived from a variety of sources', 'The restaurant has an eclectic menu.'),
('effusive', '热情洋溢的', 'showing extreme enthusiasm', 'She gave an effusive thank-you speech.'),
('elaborate', '精心制作的', 'carefully prepared', 'They created an elaborate plan.'),
('elusive', '难以捉摸的', 'difficult to find', 'The elusive criminal remained at large.'),
('eloquent', '雄辩的', 'fluent and persuasive', 'The eloquent speaker captivated the audience.'),
('eminent', '杰出的', 'famous and respected', 'He is an eminent scientist.'),
('empirical', '实证的', 'based on observation', 'Empirical evidence supports the theory.'),
('enigmatic', '神秘的', 'difficult to interpret', 'The enigmatic painting puzzled art critics.'),
('ephemeral', '短暂的', 'lasting for a very short time', 'Youth is an ephemeral gift.'),
('equitable', '公平的', 'fair and impartial', 'The equitable distribution of resources is essential.'),
('erudite', '博学的', 'having or showing great knowledge', 'The erudite professor wrote many books.'),
('esoteric', '深奥的', 'intended for or likely to be understood', 'The esoteric subject was beyond most students.'),
('euphemistic', '委婉的', 'using polite words', 'He used a euphemistic expression to avoid offense.'),
('exacting', '严格的', 'demanding accuracy', 'The exacting standards ensured quality.'),
('exasperating', '令人恼怒的', 'extremely annoying', 'His constant delays were exasperating.'),
('exigent', '紧急的', 'requiring immediate action', 'The exigent situation needed urgent attention.'),
('exorbitant', '过高的', 'unreasonably high', 'The hotel charged an exorbitant price.'),
('extemporaneous', '即兴的', 'done without preparation', 'He gave an extemporaneous speech.'),
('fallacious', '谬误的', 'based on a mistaken belief', 'The fallacious argument was quickly refuted.'),
('fastidious', '挑剔的', 'very attentive to detail', 'The fastidious chef inspected every dish.'),
('fatuous', '愚蠢的', 'silly and pointless', 'His fatuous comments amused no one.'),
('fecund', '肥沃的', 'producing many offspring', 'The fecund soil yielded a good harvest.'),
('fervent', '热烈的', 'having or showing strong feelings', 'She had a fervent belief in justice.'),
('fickle', '善变的', 'changing frequently', 'The fickle weather made it hard to plan.'),
('florid', '华丽的', 'elaborately or excessively decorated', 'The florid prose was hard to read.'),
('foppish', '浮华的', 'excessively concerned with dress', 'He had a foppish sense of style.'),
('furtive', '偷偷的', 'attempting to avoid notice', 'He made a furtive glance around the room.'),
('garrulous', '饶舌的', 'talkative', 'The garrulous old man wouldn''t stop talking.'),
('gregarious', '合群的', 'fond of company', 'She is a gregarious person who loves parties.'),
('guileless', '坦率的', 'innocent and without deception', 'His guileless nature made him popular.'),
('hackneyed', '陈腐的', 'lacking freshness', 'The movie used a hackneyed plot device.'),
('halcyon', '平静的', 'denoting a period of time', 'They remembered the halcyon days of their youth.'),
('hapless', '不幸的', 'unfortunate', 'The hapless traveler missed his flight.'),
('hedonistic', '享乐主义的', 'pursuing pleasure', 'He led a hedonistic lifestyle.'),
('heretical', '异教的', 'contrary to accepted beliefs', 'His heretical ideas were controversial.'),
('histrionic', '夸张的', 'excessively theatrical', 'Her histrionic outburst was unnecessary.'),
('hubristic', '傲慢的', 'excessively proud', 'His hubristic attitude led to his downfall.'),
('hypocritical', '虚伪的', 'pretending to have moral standards', 'His hypocritical behavior was exposed.'),
('iconoclastic', '反传统的', 'attacking or rejecting cherished beliefs', 'The iconoclastic artist challenged conventions.'),
('idiosyncratic', '独特的', 'relating to a person''s quirks', 'He had an idiosyncratic style of dressing.'),
('impassioned', '充满激情的', 'showing strong feelings', 'She gave an impassioned speech.'),
('impeccable', '完美的', 'faultless', 'His impeccable manners impressed everyone.'),
('impetuous', '冲动的', 'acting or done quickly', 'His impetuous decision led to problems.'),
('implacable', '难以平息的', 'unable to be appeased', 'The implacable enemy refused to negotiate.'),
('imprecise', '不精确的', 'not exact', 'The imprecise instructions caused confusion.'),
('improbable', '不太可能的', 'not likely to be true', 'The improbable story was hard to believe.'),
('impudent', '无礼的', 'not showing due respect', 'His impudent remarks were offensive.'),
('inadvertent', '无意中的', 'not resulting from or achieved', 'The inadvertent mistake was quickly corrected.'),
('inane', '空洞的', 'silly and stupid', 'The inane conversation bored everyone.'),
('incisive', '敏锐的', 'showing good judgment', 'The incisive analysis uncovered the truth.'),
('inconsequential', '不重要的', 'not important', 'The inconsequential detail was overlooked.'),
('indefatigable', '不知疲倦的', 'persistently energetic', 'The indefatigable worker completed the task.'),
('indifferent', '冷漠的', 'having no particular interest', 'He seemed indifferent to the news.'),
('indiscreet', '不谨慎的', 'not showing good judgment', 'Her indiscreet comments caused trouble.'),
('ineffable', '难以形容的', 'too great to be described', 'The beauty of the sunset was ineffable.'),
('inept', '无能的', 'having no skill', 'The inept manager made many mistakes.'),
('ineluctable', '不可避免的', 'unable to be avoided', 'Death is an ineluctable fact of life.'),
('inert', '无活力的', 'lacking the ability to move', 'The inert rock lay where it had fallen.'),
('inexorable', '不可阻挡的', 'unable to be stopped', 'The inexorable progress of technology continues.'),
('infamous', '臭名昭著的', 'well known for being bad', 'The infamous criminal was finally caught.'),
('ingenuous', '天真的', 'innocent and unsuspecting', 'His ingenuous nature made him easy to deceive.'),
('insatiable', '贪得无厌的', 'impossible to satisfy', 'He had an insatiable appetite for knowledge.'),
('inscrutable', '神秘的', 'impossible to understand', 'His inscrutable expression gave nothing away.'),
('insidious', '阴险的', 'proceeding in a gradual', 'The insidious disease slowly affected his health.'),
('insipid', '乏味的', 'lacking flavor', 'The insipid food was unappetizing.'),
('intangible', '无形的', 'unable to be touched', 'Happiness is an intangible concept.'),
('intransigent', '不妥协的', 'unwilling to change', 'The intransigent negotiator refused to budge.'),
('inundated', '淹没的', 'overwhelmed with things', 'She was inundated with requests for help.'),
('invidious', '招人反感的', 'likely to arouse resentment', 'The invidious comparison offended many.'),
('irascible', '易怒的', 'easily angered', 'The irascible old man shouted at the children.'),
('irksome', '讨厌的', 'annoying', 'The irksome noise kept her awake.'),
('jaunty', '活泼的', 'cheerful and lively', 'He walked with a jaunty step.'),
('judicious', '明智的', 'showing good judgment', 'The judicious decision saved the company.'),
('jubilant', '欢腾的', 'feeling or expressing great happiness', 'The jubilant crowd celebrated the victory.'),
('laconic', '简洁的', 'using very few words', 'His laconic reply left us wondering.'),
('languid', '无精打采的', 'lacking energy', 'The languid afternoon made everyone sleepy.'),
('lavish', '奢侈的', 'sumptuously rich', 'They had a lavish wedding.'),
('lethargic', '无精打采的', 'sluggish and lacking energy', 'The lethargic dog lay in the sun.'),
('loquacious', '健谈的', 'talking a great deal', 'The loquacious stranger wouldn''t stop chatting.'),
('luminous', '发光的', 'giving off light', 'The luminous moon lit up the sky.'),
('magnanimous', '宽宏大量的', 'generous and forgiving', 'The magnanimous winner praised his opponent.'),
('malevolent', '恶意的', 'having or showing a wish', 'The malevolent villain plotted revenge.'),
('malleable', '可塑的', 'able to be hammered', 'Clay is a malleable material.'),
('mendacious', '虚假的', 'dishonest', 'The mendacious politician lied to the public.'),
('mercurial', '多变的', 'subject to sudden or unpredictable changes', 'His mercurial mood made him hard to deal with.'),
('meticulous', '一丝不苟的', 'showing great attention to detail', 'The meticulous worker checked every item.'),
('mollifying', '抚慰的', 'intended to reduce anger', 'She made a mollifying gesture.'),
('morose', '忧郁的', 'sullen and ill-tempered', 'He was in a morose mood all day.'),
('mundane', '平凡的', 'lacking interest', 'The mundane tasks seemed endless.'),
('myopic', '短视的', 'unable to see the long-term', 'The myopic decision led to problems later.'),
('nefarious', '邪恶的', 'wicked', 'The nefarious scheme was foiled.'),
('negligent', '疏忽的', 'failing to take proper care', 'The negligent driver caused the accident.'),
('niggardly', '吝啬的', 'ungenerous', 'His niggardly donation was disappointing.'),
('noisome', '令人不快的', 'unpleasant or offensive', 'The noisome odor filled the room.'),
('noxious', '有害的', 'harmful', 'The noxious fumes were dangerous.'),
('obdurate', '顽固的', 'stubbornly refusing', 'The obdurate child refused to eat.'),
('obfuscate', '使模糊', 'make obscure', 'The politician tried to obfuscate the issue.'),
('obsequious', '谄媚的', 'showing excessive flattery', 'The obsequious servant annoyed everyone.'),
('obtuse', '迟钝的', 'slow to understand', 'He was surprisingly obtuse about the problem.'),
('occurrent', '正在发生的', 'happening now', 'The occurrent events are being reported.'),
('onerous', '繁重的', 'involving a great deal of effort', 'The onerous task took weeks to complete.'),
('opulent', '富裕的', 'wealthy and luxurious', 'The opulent mansion was impressive.'),
('ostentatious', '炫耀的', 'characterized by vulgar', 'His ostentatious display of wealth was distasteful.'),
('parsimonious', '吝啬的', 'very unwilling to spend money', 'The parsimonious CEO cut all unnecessary expenses.'),
('pedantic', '迂腐的', 'showing excessive attention', 'The pedantic professor corrected every minor error.'),
('penurious', '贫困的', 'extremely poor', 'The penurious family struggled to survive.'),
('perfunctory', '敷衍的', 'done with little care', 'He gave a perfunctory apology.'),
('pernicious', '有害的', 'having a harmful effect', 'The pernicious influence corrupted him.'),
('perspicacious', '敏锐的', 'having keen perception', 'The perspicacious detective solved the case.'),
('petulant', '任性的', 'childishly sulky', 'The petulant child refused to share.'),
('phlegmatic', '冷静的', 'unemotional and calm', 'His phlegmatic nature helped in a crisis.'),
('pithy', '简洁的', 'concise and full of meaning', 'She gave a pithy summary.'),
('placate', '安抚', 'make (someone) less angry', 'He tried to placate the upset customer.'),
('platitudinous', '陈词滥调的', 'full of clichés', 'The speech was platitudinous and boring.'),
('pliant', '易弯曲的', 'easily bent', 'The pliant material could be shaped easily.'),
('prodigal', '挥霍的', 'spending money', 'The prodigal son wasted his inheritance.'),
('profligate', '挥霍的', 'recklessly extravagant', 'His profligate lifestyle led to bankruptcy.'),
('prosaic', '平淡的', 'lacking imagination', 'The prosaic description made the story dull.'),
('pragmatic', '务实的', 'dealing with things', 'A pragmatic approach is needed.'),
('precarious', '危险的', 'not securely held', 'The precarious situation required caution.'),
('precipitous', '陡峭的', 'very steep', 'The precipitous cliff was dangerous.'),
('prejudiced', '有偏见的', 'having or showing bias', 'The prejudiced attitude was unacceptable.'),
('prevaricate', '支吾', 'speak or act in an evasive way', 'He tried to prevaricate when questioned.'),
('pristine', '原始的', 'in its original condition', 'The pristine forest was untouched.'),
('prolix', '冗长的', 'using too many words', 'The prolix essay was hard to read.'),
('puerile', '幼稚的', 'childish', 'His puerile behavior annoyed his colleagues.'),
('punctilious', '一丝不苟的', 'showing great attention', 'The punctilious secretary never made a mistake.'),
('quixotic', '不切实际的', 'extremely idealistic', 'His quixotic plan was doomed to fail.'),
('rarefied', '高雅的', 'existing in a high', 'The rarefied world of classical music'),
('rebarbative', '令人反感的', 'unpleasant and unattractive', 'His rebarbative personality made him unpopular.'),
('recalcitrant', '顽固的', 'stubbornly uncooperative', 'The recalcitrant student refused to listen.'),
('redolent', '芬芳的', 'strongly reminiscent', 'The air was redolent of roses.'),
('refractory', '难处理的', 'stubbornly resistant', 'The refractory metal was hard to shape.'),
('reticent', '沉默寡言的', 'not revealing one''s thoughts', 'He was reticent about his past.'),
('rhetorical', '修辞的', 'relating to rhetoric', 'The rhetorical question needed no answer.'),
('sagacious', '明智的', 'having or showing good judgment', 'The sagacious leader made wise decisions.'),
('salubrious', '有益健康的', 'health-giving', 'The salubrious climate helped her recover.'),
('sanctimonious', '伪善的', 'making a show of being morally', 'His sanctimonious attitude was hypocritical.'),
('sardonic', '讽刺的', 'grimly mocking', 'He gave a sardonic laugh.'),
('sanguine', '乐观的', 'optimistic', 'She remained sanguine despite the difficulties.'),
('scrupulous', '审慎的', 'acting with great care', 'The scrupulous accountant checked every figure.'),
('sedulous', '勤勉的', 'showing dedication', 'The sedulous worker completed the project on time.'),
('seditious', '煽动性的', 'inciting rebellion', 'The seditious speech was banned.'),
('serene', '平静的', 'calm and peaceful', 'The serene lake was beautiful.'),
('sibilant', '嘶嘶声的', 'characterized by a hissing sound', 'The sibilant whisper was hard to hear.'),
('specious', '似是而非的', 'appearing to be true', 'The specious argument was easily disproven.'),
('spurious', '虚假的', 'not being what it purports to be', 'The spurious document was a forgery.'),
('stalwart', '坚定的', 'loyal and reliable', 'The stalwart supporter never gave up.'),
('stentorian', '洪亮的', 'loud and powerful', 'The stentorian voice echoed through the hall.'),
('stodgy', '古板的', 'dull and uninteresting', 'The stodgy professor''s lectures were boring.'),
('strident', '刺耳的', 'loud and harsh', 'The strident noise made her ears hurt.'),
('stultifying', '令人窒息的', 'causing someone to lose热情', 'The stultifying job drained his energy.'),
('sublime', '崇高的', 'of very great excellence', 'The sublime music moved the audience.'),
('supercilious', '傲慢的', 'behaving or looking as though', 'The supercilious waiter ignored us.'),
('surreptitious', '秘密的', 'kept secret', 'He made a surreptitious glance at his watch.'),
('taciturn', '沉默寡言的', 'reserved', 'The taciturn man rarely spoke.'),
('tangential', '离题的', 'only slightly relevant', 'The tangential comment distracted from the main point.'),
('tenacious', '顽强的', 'persistent', 'The tenacious athlete never gave up.'),
('tendentious', '有偏见的', 'showing strong bias', 'The tendentious article was unfair.'),
('timorous', '胆小的', 'showing fear', 'The timorous child clung to his mother.'),
('torpid', '迟钝的', 'mentally or physically inactive', 'The torpid animal slept all day.'),
('trenchant', '尖锐的', 'vigorous and incisive', 'The trenchant criticism exposed the flaws.'),
('truculent', '好斗的', 'aggressively hostile', 'The truculent dog barked at everyone.'),
('turgid', '浮夸的', 'excessively ornate', 'The turgid prose was hard to understand.'),
('ubiquitous', '无处不在的', 'present everywhere', 'Advertising has become ubiquitous.'),
('unctuous', '油滑的', 'excessively flattering', 'The unctuous salesman made her uncomfortable.'),
('urbane', '文雅的', 'polished and sophisticated', 'The urbane gentleman impressed everyone.'),
('usurious', '高利贷的', 'involving exorbitant interest', 'The usurious loan trapped him in debt.'),
('vacuous', '空洞的', 'lacking intelligence', 'The vacuous expression on his face showed he wasn''t listening.'),
('vainglorious', '自负的', 'characterized by excessive pride', 'The vainglorious actor boasted about his achievements.'),
('variegated', '杂色的', 'having different colors', 'The variegated leaves added beauty to the garden.'),
('verbose', '冗长的', 'using too many words', 'The verbose report could have been shorter.'),
('vexatious', '令人烦恼的', 'causing annoyance', 'The vexatious problem refused to be solved.'),
('vilify', '诋毁', 'speak of in a negative way', 'The politician tried to vilify his opponent.'),
('vindictive', '报复性的', 'having or showing a strong desire', 'The vindictive employee spread rumors.'),
('virulent', '恶毒的', 'extremely hostile', 'The virulent criticism was uncalled for.'),
('viscous', '粘性的', 'having a thick consistency', 'The viscous liquid was hard to pour.'),
('voluble', '健谈的', 'talking fluently', 'The voluble guest wouldn''t stop talking.'),
('voracious', '贪婪的', 'having an insatiable appetite', 'The voracious reader devoured books.'),
('wary', '谨慎的', 'feeling or showing caution', 'The wary investor researched before buying.'),
('whimsical', '异想天开的', 'playfully quaint', 'The whimsical story delighted the children.'),
('wilful', '任性的', 'deliberately obstinate', 'The wilful child refused to cooperate.'),
('winsome', '迷人的', 'attractive in a fresh', 'The winsome smile brightened the room.'),
('wistful', '惆怅的', 'having or showing a feeling', 'He gave a wistful look at his childhood home.'),
('wrathful', '愤怒的', 'very angry', 'The wrathful customer demanded a refund.'),
('xenophobic', '排外的', 'having or showing a dislike', 'The xenophobic attitude was unwelcome.'),
('yeomanly', '勇敢的', 'showing determination', 'The yeomanly effort saved the project.'),
('zealous', '热情的', 'having or showing zeal', 'The zealous fans cheered their team.'),
('zesty', '有活力的', 'full of energy and enthusiasm', 'The zesty performance entertained the crowd.');
    